export const MockedRequest = {
	readable: true,
	httpVersionMajor: 1,
	httpVersionMinor: 1,
	httpVersion: '1.1',
	complete: true,
	headers: {
		host: 'localhost:3000',
		'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:75.0) Gecko/20100101 Firefox/75.0',
		accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
		'accept-language': 'en-US',
		'accept-encoding': 'gzip, deflate',
		connection: 'keep-alive',
		cookie: 'cartalyst_sentry=eyJpdiI6InE2bDdWT0t2cEZWTXJVVVNZdzBEY3c9PSIsInZhbHVlIjoiQmY3NmdkUkRySUhTWCtoUWprdU1NWitFWk1GUkFjdzRpaUVJTERWaFBUNjN2aHBNZWZvcURocXRsNHJFalZnWmVWaXFkM0txN0c5ZndLV25FcUR4Zk1KaTNqRDU2V3VpNEROMFpOa3FzSFwvUnFKNXI3c3FBMDMwZDlZeVlZUkx5IiwibWFjIjoiMGQ2MDM0ZTRiMzIwMTBhMTZjYzc0NzY3MDRhYmE2NTdkZGZiZmU2N2YxMDNjZTM5NGZiOTJhMWQ5YTAyY2ZhZiJ9; i18n_redirected=en; experimentation_subject_id=IjlkYWU1Yzc4LTU0N2MtNDNhZS04NDMyLWE4NTUyN2EwOTYwZSI%3D--ad90b9d228aecd0424986c55629f5ad1f6862b6b; sidebar_collapsed=false',
		'upgrade-insecure-requests': '1',
		'cache-control': 'max-age=0'
	},
	rawHeaders: [
		'Host',
		'localhost:3000',
		'User-Agent',
		'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:75.0) Gecko/20100101 Firefox/75.0',
		'Accept',
		'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
		'Accept-Language',
		'en-US',
		'Accept-Encoding',
		'gzip, deflate',
		'Connection',
		'keep-alive',
		'Cookie',
		'cartalyst_sentry=eyJpdiI6InE2bDdWT0t2cEZWTXJVVVNZdzBEY3c9PSIsInZhbHVlIjoiQmY3NmdkUkRySUhTWCtoUWprdU1NWitFWk1GUkFjdzRpaUVJTERWaFBUNjN2aHBNZWZvcURocXRsNHJFalZnWmVWaXFkM0txN0c5ZndLV25FcUR4Zk1KaTNqRDU2V3VpNEROMFpOa3FzSFwvUnFKNXI3c3FBMDMwZDlZeVlZUkx5IiwibWFjIjoiMGQ2MDM0ZTRiMzIwMTBhMTZjYzc0NzY3MDRhYmE2NTdkZGZiZmU2N2YxMDNjZTM5NGZiOTJhMWQ5YTAyY2ZhZiJ9; sidebar_collapsed=false',
		'Upgrade-Insecure-Requests',
		'1',
		'Cache-Control',
		'max-age=0'
	],
	trailers: {},
	rawTrailers: [],
	aborted: false,
	upgrade: false,
	url: '/',
	method: 'GET',
	statusCode: null,
	statusMessage: null,
	_consuming: false,
	_dumped: false,
	baseUrl: '',
	originalUrl: '/',
	params: {},
	query: {
		name: 'Onur',
		surname: 'Ozkan'
	},
	body: {},
}

